### ISSUE TITLE
Installation lab

### ISSUE THREAD

**Issue by goelph** [goelph/SEBC#1]
Beginning installation.

**Comment by goelph** [comment]
I will be using Plan 2 for the mysql installation

**Comment by goelph** [comment]
Cloudera SCM server will not start.

It is complaining about "Failed to start LSB: Cloudera SCM Server."

Sep 19 23:07:35 localhost systemd: Starting LSB: Cloudera SCM Server...
Sep 19 23:07:35 localhost su: (to cloudera-scm) root on none
Sep 19 23:07:35 localhost systemd: Created slice user-995.slice.
Sep 19 23:07:35 localhost systemd: Starting user-995.slice.
Sep 19 23:07:35 localhost systemd: Started Session c6 of user cloudera-scm.
Sep 19 23:07:35 localhost systemd: Starting Session c6 of user cloudera-scm.
Sep 19 23:07:37 localhost systemd: Removed slice user-995.slice.
Sep 19 23:07:37 localhost systemd: Stopping user-995.slice.
Sep 19 23:07:40 localhost cloudera-scm-server: Starting cloudera-scm-server: [FAILED]
Sep 19 23:07:40 localhost systemd: cloudera-scm-server.service: control process exited, code=exited status=1
Sep 19 23:07:40 localhost systemd: Failed to start LSB: Cloudera SCM Server.
Sep 19 23:07:40 localhost systemd: Unit cloudera-scm-server.service entered failed state.
Sep 19 23:07:40 localhost systemd: cloudera-scm-server.service failed.

**Comment by goelph** [comment]
This should be finished at this point.

**Comment by mfernest** [comment]
I'll evaluate this lab as soon as I have seen every repo one time.

**Comment by mfernest** [comment]
Nice clean work -- no complaints.

Completed.
