### ISSUE TITLE
Storage Labs

### ISSUE THREAD

**Issue by goelph** [goelph/SEBC#2]
Starting work on the 4 sections of labs

**Comment by goelph** [comment]
Can't procede further without more disk space.  That 10 GB file really tears up the four datanodes, and now I have .Trash to take out as well.

**Comment by goelph** [comment]
Disabled Trash, had to run hdfs dfs -expunge to remove old trash files.  Freed up about 100 G across the 4 nodes when problems occurred initially.  This was due to trying to create file 100 times larger than 10 GB (due to not figuring the 100 bytes per row info correctly the first time).

**Comment by goelph** [comment]
Only remaining thing to do here is the cluster-to-cluster file replication

**Comment by goelph** [comment]
screenshot from failed replication indicating timeout between hosts

**Comment by goelph** [comment]
updated status

**Comment by mfernest** [comment]
Sure do appreciate the running dialog -- cuts my work in half, at the least.

Completed.
