### ISSUE TITLE
Resource Labs

### ISSUE THREAD

**Issue by goelph** [goelph/SEBC#3]
Started YARN labs

**Comment by goelph** [comment]
Step 2 finished (Static Service Pools)

**Comment by goelph** [comment]
Step 1 finished (MATH)

**Comment by goelph** [comment]
Run 1: Loop will be for 2 mappers/2 reducers and JVM heap ranging from 512 to 1024 MB
Testing loop started on Wed Sep 21 11:44:02 EDT 2016
mapper # 2
reducer # 2
container memory 512
Deleted /user/goelph/results/tg-10GB-2-2-512
Deleted /user/goelph/results/ts-10GB-2-2-512
container memory 1024
Deleted /user/goelph/results/tg-10GB-2-2-1024
Deleted /user/goelph/results/ts-10GB-2-2-1024
Testing loop ended on Wed Sep 21 11:45:34 EDT 2016

real    1m31.310s
user    0m42.758s
sys     0m1.297s

**Comment by mfernest** [comment]
This output is fine. For the lab results, I'd like to see at least the parameters (mapper count, container size, etc.) and the time. Just ensure the job ran successfully.

**Comment by goelph** [comment]
YARNtest info uploaded.

**Comment by mfernest** [comment]
Completed.
