### ISSUE TITLE
Clients Lab

### ISSUE THREAD

**Issue by goelph** [goelph/SEBC#6]
the utility does not appear to work.  Something about password

**Comment by goelph** [comment]
CURRENT PROBLEM:

# cd /opt/cloudera/parcels/CDH/lib/hue

[root@ip-172-31-63-3 hue]# ls
app.reg  cloudera  LICENSE.txt  Makefile.buildvars  Makefile.vars.priv  tools
apps     desktop   logs         Makefile.sdk        NOTICE.txt          VERSION
build    ext       Makefile     Makefile.vars       README
[root@ip-172-31-63-3 hue]# build/env/bin/hue useradmin_sync_with_unix
Error: Password not present
subprocess.CalledProcessError: Command 
'/run/cloudera-scm-agent/process/255-hue-HUE_SERVER/altscript.sh sec-5-password' 
returned non-zero exit status 1

**Comment by goelph** [comment]
found another document mentioning the HUE_DATABASE_PASSWORD variable.  Set and imported users.  Still have to change passwords for them before they can log on -- but that's ok, 'cuz you also need to add them to a group with access to apps ...

**Comment by mfernest** [comment]
Completed.
